# Generated by Django 5.2.1 on 2025-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_comment_level_comment_lft_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=150),
        ),
    ]
